05-dom-doc
js-tasks-ru/js-20210427_ditochilin pull request #6
Opened 2021-05-21 09:12 UTC by ditochilin

для sortable-table-v1 не проходят два теста - не понял из-за чего(
    × should sort "asc" correctly for "sortType" equal number (17ms)
    × should sort "desc" correctly for "sortType" equal number (13ms)
    
    Хотя сама таблица по прайсу сортирется корректно

2021-05-21 09:12 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-05-21 13:28 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +        <div class="sortable-table__cell">${item.quantity}</div>
так делать нельзя. К свойствам `quantity`, `title`, `price` ... нельзя обращаться напрямую, ведь таблица может отобразить любые данные

2021-05-21 13:28 UTC, dosandk requested changes
SortableTable следует поправить

2021-05-24 13:41 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +    initialize() {
good 👍

2021-05-24 13:41 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +            document.addEventListener('pointermove', this.onPointerMove);
good 👍

2021-05-24 13:41 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +        targetElems.forEach(item => item.removeEventListener('pointerover', this.onStartShowToolTip));
здесь нет необходимости снимать обработчики с элемента

2021-05-24 13:42 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +    this.element.querySelector('[data-element="header"]').removeEventListener('pointerdown', this.onClickHeaderHandler);
здесь нет необходимости удалять обработчики с элемента

2021-05-24 13:42 UTC, dosandk approved these changes
good 👍

2021-05-24 13:43 UTC, merged